// Rewrites img/CREDITS.md from img/sources.json, and names any image with no entry.
// The JSON is the record; the markdown is for reading. `make credits`.

import { IMG_DIR } from './content.ts';

type Source = { source?: string; author?: string; licence?: string };

const SOURCES = new URL('sources.json', IMG_DIR);
const CREDITS = new URL('CREDITS.md', IMG_DIR);

const sources: Record<string, Source> = JSON.parse(await Deno.readTextFile(SOURCES));

const images: string[] = [];
for await (const entry of Deno.readDir(IMG_DIR)) {
  if (entry.isFile && /\.(jpe?g|png|webp)$/i.test(entry.name)) images.push(entry.name);
}
images.sort();

const rows = images.map((file) => {
  const s = sources[file] ?? {};
  const where = s.source ? `[link](${s.source})` : '**missing**';
  return `| \`${file}\` | ${where} | ${s.author || '-'} | ${s.licence || 'unknown'} |`;
});

await Deno.writeTextFile(
  CREDITS,
  [
    '<!-- GENERATED by scripts/credits.ts from sources.json. Run `make credits`. -->',
    '',
    '# Image sources',
    '',
    'Where each picture came from. CC BY and CC BY-SA require the attribution to be kept;',
    'public domain and CC0 do not, and are recorded so an image can be re-sourced later.',
    '',
    '| file | source | author | licence |',
    '| --- | --- | --- | --- |',
    ...rows,
    '',
  ].join('\n'),
);

const missing = images.filter((file) => !sources[file]?.source);
console.log(`${images.length} images, ${images.length - missing.length} with a source`);
if (missing.length > 0) console.log(`no source recorded: ${missing.join(', ')}`);
