// Reads content/*.md (one Markdown file per topic, YAML-ish frontmatter + a bullet list
// of facts) and writes two generated, gitignored TypeScript modules:
//
//   api/db/content.generated.ts        — PAGE_IDS, as a literal `as const` array
//   client/src/data/pages.generated.ts — PAGES, as a literal Page[] array
//
// This is the single source both apps read PAGE_IDS/PAGES from, so there is nothing left
// to hand-duplicate between client and server. Run via `make generate-content`, or
// `make dev` / `make build` / `make check`, which depend on it.
//
// No YAML library and no schema validator: the frontmatter here is flat scalar
// `key: value` pairs, so a full parser buys nothing, and the checks below fail loudly
// enough (file name + missing field) that a validator would mostly repeat the message.

type Page = {
  id: string;
  order: number;
  title: string;
  emoji: string;
  blurb: string;
  facts: string[];
};

const CONTENT_DIR = new URL('../content/', import.meta.url);
const API_OUT = new URL('../api/db/content.generated.ts', import.meta.url);
const CLIENT_OUT = new URL('../client/src/data/pages.generated.ts', import.meta.url);

function parseFrontmatter(raw: string, filename: string): Record<string, string> {
  const fields: Record<string, string> = {};
  for (const line of raw.split('\n')) {
    if (!line.trim()) continue;
    const match = line.match(/^([a-zA-Z][a-zA-Z0-9_]*):\s*(.*)$/);
    if (!match) throw new Error(`${filename}: unparseable frontmatter line: ${JSON.stringify(line)}`);
    fields[match[1]] = match[2].trim();
  }
  return fields;
}

function parseFacts(body: string): string[] {
  return body
    .split('\n')
    .filter((line) => line.trimStart().startsWith('- '))
    .map((line) => line.trim().slice(2).trim());
}

function requireField(fields: Record<string, string>, name: string, filename: string): string {
  const value = fields[name];
  if (!value) throw new Error(`${filename}: missing required frontmatter field "${name}"`);
  return value;
}

async function loadPage(entryName: string): Promise<Page> {
  const stem = entryName.replace(/\.md$/, '');
  const raw = await Deno.readTextFile(new URL(entryName, CONTENT_DIR));

  const frontmatterMatch = raw.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!frontmatterMatch) throw new Error(`${entryName}: expected leading --- frontmatter block`);
  const [, frontmatterRaw, body] = frontmatterMatch;

  const fields = parseFrontmatter(frontmatterRaw, entryName);

  const id = requireField(fields, 'id', entryName);
  if (id !== stem) throw new Error(`${entryName}: frontmatter id "${id}" must match the filename ("${stem}")`);

  const orderRaw = requireField(fields, 'order', entryName);
  const order = Number(orderRaw);
  if (!Number.isFinite(order)) throw new Error(`${entryName}: order "${orderRaw}" is not a number`);

  const title = requireField(fields, 'title', entryName);
  const emoji = requireField(fields, 'emoji', entryName);
  const blurb = requireField(fields, 'blurb', entryName);

  const facts = parseFacts(body);
  if (facts.length === 0) throw new Error(`${entryName}: no facts found — expected a Markdown bullet list ("- ...")`);

  return { id, order, title, emoji, blurb, facts };
}

async function loadPages(): Promise<Page[]> {
  const entries: string[] = [];
  for await (const entry of Deno.readDir(CONTENT_DIR)) {
    if (entry.isFile && entry.name.endsWith('.md')) entries.push(entry.name);
  }
  if (entries.length === 0) throw new Error(`no content found in ${CONTENT_DIR.pathname}`);

  const pages = await Promise.all(entries.map(loadPage));
  pages.sort((a, b) => a.order - b.order);

  const seen = new Set<string>();
  for (const page of pages) {
    if (seen.has(page.id)) throw new Error(`duplicate content id: "${page.id}"`);
    seen.add(page.id);
  }

  return pages;
}

const HEADER =
  '// GENERATED by scripts/generate-content.ts from content/*.md — do not edit by hand.\n' +
  '// Rerun `make generate-content` (or `make dev` / `make build` / `make check`, which do\n' +
  '// this for you) after changing anything under content/.\n\n';

function renderApiModule(pages: Page[]): string {
  const ids = pages.map((p) => JSON.stringify(p.id));
  return `${HEADER}export const PAGE_IDS = [\n${ids.map((id) => `  ${id},`).join('\n')}\n] as const;\n`;
}

function renderClientModule(pages: Page[]): string {
  const literal = JSON.stringify(
    pages.map(({ id, title, emoji, blurb, facts }) => ({ id, title, emoji, blurb, facts })),
    null,
    2,
  );
  return `${HEADER}import type { Page } from './pages';\n\nexport const PAGES: Page[] = ${literal};\n`;
}

const pages = await loadPages();
await Deno.writeTextFile(API_OUT, renderApiModule(pages));
await Deno.writeTextFile(CLIENT_OUT, renderClientModule(pages));
console.log(`generated ${pages.length} pages from content/ -> ${API_OUT.pathname}, ${CLIENT_OUT.pathname}`);
