// Reads content/*.md (see scripts/content.ts for the format) and writes two generated,
// gitignored TypeScript modules:
//
//   api/db/content.generated.ts        — PAGE_IDS, as a literal `as const` array
//   client/src/data/pages.generated.ts — PAGES, as a literal Page[] array
//
// This is the single source both apps read PAGE_IDS/PAGES from, so there is nothing left
// to hand-duplicate between client and server. Run via `make generate-content`, or
// `make dev` / `make build` / `make check`, which depend on it.

import { audioFileUrl, loadPages, type Page, SFX_DIR, SFX_SOURCE_EXTENSIONS, slug, soundFileUrl } from './content.ts';

const API_OUT = new URL('../api/db/content.generated.ts', import.meta.url);
const CLIENT_OUT = new URL('../client/src/data/pages.generated.ts', import.meta.url);

// A word whose clip is missing would render a play button that does nothing, and the
// failure would only show up on a device with the volume up. Failing the build instead
// means content and audio assets cannot drift — including on Deno Deploy, where this runs
// as the first step of `deno task build`.
// slug() folds å/ä/ö onto a/a/o, so "har" (have) and "här" (here) both want har.m4a. The
// same word appearing on two pages is fine and shares one clip; two *different* words
// landing on one filename would silently swap one child's word for another's, and
// generate-audio would overwrite whichever it wrote first.
function assertNoSlugCollisions(pages: Page[]): void {
  const owners = new Map<string, { sv: string; page: string }>();

  for (const page of pages) {
    for (const word of page.words) {
      const key = slug(word.sv);
      const owner = owners.get(key);
      if (!owner) owners.set(key, { sv: word.sv, page: page.id });
      else if (owner.sv !== word.sv) {
        throw new Error(
          `both "${owner.sv}" (${owner.page}) and "${word.sv}" (${page.id}) derive /media/${key}.m4a — ` +
            'rename one, or give it a distinct spelling',
        );
      }
    }
  }
}

async function assertClipsExist(pages: Page[]): Promise<void> {
  const missing: string[] = [];

  for (const page of pages) {
    for (const word of page.words) {
      const url = audioFileUrl(word);
      try {
        await Deno.stat(url);
      } catch {
        missing.push(`  ${page.id}: "${word.sv}" -> ${url.pathname}`);
      }
    }
  }

  if (missing.length > 0) {
    throw new Error(
      `missing audio clips:\n${missing.join('\n')}\n` +
        'Run `make generate-audio` on macOS, then commit the clips.',
    );
  }
}

// Sound effect filenames are authored, not derived, so a typo is the likely failure —
// caught here rather than as a button that does nothing on the iPad.
async function assertSoundsExist(pages: Page[]): Promise<void> {
  const missing: string[] = [];

  for (const page of pages) {
    for (const sound of page.sounds) {
      const url = soundFileUrl(sound);
      try {
        await Deno.stat(url);
      } catch {
        missing.push(`  ${page.id}: "${sound.label}" -> ${url.pathname}`);
      }
    }
  }

  if (missing.length > 0) {
    throw new Error(
      `missing sound effects:\n${missing.join('\n')}\n` +
        'Drop the file in client/static/media/sfx/ and run `make convert-sfx` on macOS.',
    );
  }
}

// The build copies static/ wholesale, so an unconverted download ships next to the .m4a
// it produced — twice the bytes, for a file nothing references. `make convert-sfx` deletes
// its own sources; this catches the ones dragged in by hand and forgotten.
async function assertSourcesConverted(): Promise<void> {
  const leftovers: string[] = [];

  try {
    for await (const entry of Deno.readDir(SFX_DIR)) {
      if (!entry.isFile) continue;
      const dot = entry.name.lastIndexOf('.');
      const extension = dot === -1 ? '' : entry.name.slice(dot).toLowerCase();
      if (SFX_SOURCE_EXTENSIONS.includes(extension)) leftovers.push(`  ${entry.name}`);
    }
  } catch {
    return; // no sfx/ yet
  }

  if (leftovers.length > 0) {
    throw new Error(
      `unconverted sound sources in client/static/media/sfx/:\n${leftovers.join('\n')}\n` +
        'Run `make convert-sfx` on macOS — it converts and then deletes them.',
    );
  }
}

const HEADER = '// GENERATED by scripts/generate-content.ts from content/*.md — do not edit by hand.\n' +
  '// Rerun `make generate-content` (or `make dev` / `make build` / `make check`, which do\n' +
  '// this for you) after changing anything under content/.\n\n';

function renderApiModule(pages: Page[]): string {
  const ids = pages.map((p) => JSON.stringify(p.id));
  return `${HEADER}export const PAGE_IDS = [\n${ids.map((id) => `  ${id},`).join('\n')}\n] as const;\n`;
}

function renderClientModule(pages: Page[]): string {
  const literal = JSON.stringify(
    // `kind` and `words` are omitted when they carry no information, so the generated
    // module stays readable and the client treats a missing `kind` as an ordinary topic.
    pages.map(({ id, kind, title, emoji, blurb, facts, words, sounds, links }) => ({
      id,
      ...(kind === 'topic' ? {} : { kind }),
      title,
      emoji,
      blurb,
      facts,
      ...(words.length > 0 ? { words } : {}),
      ...(sounds.length > 0 ? { sounds } : {}),
      ...(links.length > 0 ? { links } : {}),
    })),
    null,
    2,
  );
  return `${HEADER}import type { Page } from './pages';\n\nexport const PAGES: Page[] = ${literal};\n`;
}

const pages = await loadPages();
assertNoSlugCollisions(pages);
await assertClipsExist(pages);
await assertSoundsExist(pages);
await assertSourcesConverted();
await Deno.writeTextFile(API_OUT, renderApiModule(pages));
await Deno.writeTextFile(CLIENT_OUT, renderClientModule(pages));
console.log(`generated ${pages.length} pages from content/ -> ${API_OUT.pathname}, ${CLIENT_OUT.pathname}`);
