// content/*.md -> api/db/content.generated.ts (PAGE_IDS) and
// client/src/data/pages.generated.ts (PAGES). One source for both, so they cannot drift.
// Run by `make generate-content`, and by dev/build/check.

import { audioFileUrl, loadPages, type Page, SFX_DIR, SFX_SOURCE_EXTENSIONS, slug, soundFileUrl } from './content.ts';

const API_OUT = new URL('../api/db/content.generated.ts', import.meta.url);
const CLIENT_OUT = new URL('../client/src/data/pages.generated.ts', import.meta.url);

// slug() folds å/ä/ö, so "har" and "här" both want har.m4a. The same word twice is fine
// and shares a clip; two different words would silently swap one for the other.
function assertNoSlugCollisions(pages: Page[]): void {
  const owners = new Map<string, { sv: string; page: string }>();

  for (const page of pages) {
    for (const word of page.words) {
      const key = slug(word.sv);
      const owner = owners.get(key);
      if (!owner) owners.set(key, { sv: word.sv, page: page.id });
      else if (owner.sv !== word.sv) {
        throw new Error(
          `both "${owner.sv}" (${owner.page}) and "${word.sv}" (${page.id}) derive /media/${key}.m4a — ` +
            'rename one, or give it a distinct spelling',
        );
      }
    }
  }
}

// A missing clip is a button that does nothing, and only shows up with the volume up. This
// runs first in `deno task build`, so it is a failed deploy instead.
async function assertClipsExist(pages: Page[]): Promise<void> {
  const missing: string[] = [];

  for (const page of pages) {
    for (const word of page.words) {
      const url = audioFileUrl(word);
      try {
        await Deno.stat(url);
      } catch {
        missing.push(`  ${page.id}: "${word.sv}" -> ${url.pathname}`);
      }
    }
  }

  if (missing.length > 0) {
    throw new Error(
      `missing audio clips:\n${missing.join('\n')}\n` +
        'Run `make generate-audio` on macOS, then commit the clips.',
    );
  }
}

// Authored filenames, so a typo is the likely failure — caught here, not on the iPad.
async function assertSoundsExist(pages: Page[]): Promise<void> {
  const missing: string[] = [];

  for (const page of pages) {
    for (const sound of page.sounds) {
      const url = soundFileUrl(sound);
      try {
        await Deno.stat(url);
      } catch {
        missing.push(`  ${page.id}: "${sound.label}" -> ${url.pathname}`);
      }
    }
  }

  if (missing.length > 0) {
    throw new Error(
      `missing sound effects:\n${missing.join('\n')}\n` +
        'Drop the file in client/static/media/sfx/ and run `make convert-sfx` on macOS.',
    );
  }
}

// An unconverted download would ship beside its own output. convert-sfx deletes its
// sources; this catches ones dragged in by hand.
async function assertSourcesConverted(): Promise<void> {
  const leftovers: string[] = [];

  try {
    for await (const entry of Deno.readDir(SFX_DIR)) {
      if (!entry.isFile) continue;
      const dot = entry.name.lastIndexOf('.');
      const extension = dot === -1 ? '' : entry.name.slice(dot).toLowerCase();
      if (SFX_SOURCE_EXTENSIONS.includes(extension)) leftovers.push(`  ${entry.name}`);
    }
  } catch {
    return; // no sfx/ yet
  }

  if (leftovers.length > 0) {
    throw new Error(
      `unconverted sound sources in client/static/media/sfx/:\n${leftovers.join('\n')}\n` +
        'Run `make convert-sfx` on macOS — it converts and then deletes them.',
    );
  }
}

const HEADER = '// GENERATED by scripts/generate-content.ts from content/*.md — do not edit by hand.\n' +
  '// Rerun `make generate-content` (or `make dev` / `make build` / `make check`, which do\n' +
  '// this for you) after changing anything under content/.\n\n';

function renderApiModule(pages: Page[]): string {
  const ids = pages.map((p) => JSON.stringify(p.id));
  return `${HEADER}export const PAGE_IDS = [\n${ids.map((id) => `  ${id},`).join('\n')}\n] as const;\n`;
}

function renderClientModule(pages: Page[]): string {
  const literal = JSON.stringify(
    // Omitted when empty: a missing `kind` means topic, and the module stays readable.
    pages.map(({ id, kind, title, emoji, blurb, facts, words, sounds, links }) => ({
      id,
      ...(kind === 'topic' ? {} : { kind }),
      title,
      emoji,
      blurb,
      facts,
      ...(words.length > 0 ? { words } : {}),
      ...(sounds.length > 0 ? { sounds } : {}),
      ...(links.length > 0 ? { links } : {}),
    })),
    null,
    2,
  );
  return `${HEADER}import type { Page } from './pages';\n\nexport const PAGES: Page[] = ${literal};\n`;
}

const pages = await loadPages();
assertNoSlugCollisions(pages);
await assertClipsExist(pages);
await assertSoundsExist(pages);
await assertSourcesConverted();
await Deno.writeTextFile(API_OUT, renderApiModule(pages));
await Deno.writeTextFile(CLIENT_OUT, renderClientModule(pages));
console.log(`generated ${pages.length} pages from content/ -> ${API_OUT.pathname}, ${CLIENT_OUT.pathname}`);
