// Reads content/games/*.md and writes client/src/data/gameContent.generated.ts — the
// word/icon pairs and celebration phrases for the connect-the-words game.
//
// Client-only, unlike PAGE_IDS/PAGES: a round of this game is never sent to the server (it
// has no lives, no score, and no saved progress by design), so there is nothing for the api
// to validate and no api-side generated module.
//
// Run via `make generate-content`, alongside scripts/generate-content.ts.

import { gamePairAudioUrl, loadGamePairs, loadGamePhrases } from './gameContent.ts';

const OUT = new URL('../client/src/data/gameContent.generated.ts', import.meta.url);

// Same rationale as scripts/generate-content.ts's assertClipsExist: a missing clip should
// fail the build, not ship a tap-to-play button that plays nothing.
async function assertClipsExist(pairs: Awaited<ReturnType<typeof loadGamePairs>>): Promise<void> {
  const missing: string[] = [];

  for (const pair of pairs) {
    const url = gamePairAudioUrl(pair);
    try {
      await Deno.stat(url);
    } catch {
      missing.push(`  "${pair.sv}" -> ${url.pathname}`);
    }
  }

  if (missing.length > 0) {
    throw new Error(
      `missing audio clips for content/games/connect-pairs.md:\n${missing.join('\n')}\n` +
        'Run `make generate-audio` on macOS, then commit the clips.',
    );
  }
}

const HEADER = '// GENERATED by scripts/generate-game-content.ts from content/games/*.md — do not edit by hand.\n' +
  '// Rerun `make generate-content` (or `make dev` / `make build` / `make check`, which do\n' +
  '// this for you) after changing anything under content/games/.\n\n';

function renderModule(pairs: Awaited<ReturnType<typeof loadGamePairs>>, phrases: string[]): string {
  return `${HEADER}import type { GamePair } from './gameContent';\n\n` +
    `export const GAME_PAIRS: GamePair[] = ${JSON.stringify(pairs, null, 2)};\n\n` +
    `export const GAME_PHRASES: string[] = ${JSON.stringify(phrases, null, 2)};\n`;
}

const pairs = await loadGamePairs();
const phrases = await loadGamePhrases();
await assertClipsExist(pairs);
await Deno.writeTextFile(OUT, renderModule(pairs, phrases));
console.log(`generated ${pairs.length} game pairs and ${phrases.length} phrases -> ${OUT.pathname}`);
