// Reads content/games/*.md and writes client/src/data/gameContent.generated.ts: the
// connect-the-words pairs, the cooking shelf, the dishes, and the celebration phrases.
//
// Client-only, unlike PAGE_IDS/PAGES: a round of either game is never sent to the server
// (no lives, no score, no saved progress by design), so there is nothing for the api to
// validate and no api-side generated module.
//
// Run via `make generate-content`, alongside scripts/generate-content.ts.

import { type GamePair, gamePairAudioUrl, loadAllGamePairs, loadGamePhrases } from './gameContent.ts';

const OUT = new URL('../client/src/data/gameContent.generated.ts', import.meta.url);

// Same rationale as scripts/generate-content.ts's assertClipsExist: a missing clip should
// fail the build, not ship a tap-to-play button that plays nothing.
async function assertClipsExist(lists: Record<string, GamePair[]>): Promise<void> {
  const missing: string[] = [];

  for (const [file, pairs] of Object.entries(lists)) {
    for (const pair of pairs) {
      const url = gamePairAudioUrl(pair);
      try {
        await Deno.stat(url);
      } catch {
        missing.push(`  ${file}: "${pair.sv}" -> ${url.pathname}`);
      }
    }
  }

  if (missing.length > 0) {
    throw new Error(
      `missing audio clips for content/games/:\n${missing.join('\n')}\n` +
        'Run `make generate-audio` on macOS, then commit the clips.',
    );
  }
}

const HEADER = '// GENERATED by scripts/generate-game-content.ts from content/games/*.md — do not edit by hand.\n' +
  '// Rerun `make generate-content` (or `make dev` / `make build` / `make check`, which do\n' +
  '// this for you) after changing anything under content/games/.\n\n';

const lists = await loadAllGamePairs();
const phrases = await loadGamePhrases();
await assertClipsExist(lists);

const pairs = lists['connect-pairs.md'] ?? [];
const cooking = lists['cooking.md'] ?? [];
const dishes = lists['dishes.md'] ?? [];
const kitchen = lists['kitchen.md'] ?? [];

await Deno.writeTextFile(
  OUT,
  `${HEADER}import type { GamePair } from './gameContent';\n\n` +
    `export const GAME_PAIRS: GamePair[] = ${JSON.stringify(pairs, null, 2)};\n\n` +
    `export const COOKING_ITEMS: GamePair[] = ${JSON.stringify(cooking, null, 2)};\n\n` +
    `export const DISHES: GamePair[] = ${JSON.stringify(dishes, null, 2)};\n\n` +
    `export const KITCHEN: GamePair[] = ${JSON.stringify(kitchen, null, 2)};\n\n` +
    `export const GAME_PHRASES: string[] = ${JSON.stringify(phrases, null, 2)};\n`,
);

console.log(
  `generated ${pairs.length} pairs, ${cooking.length} ingredients, ${dishes.length} dishes, ` +
    `${kitchen.length} kitchen words, ${phrases.length} phrases -> ${OUT.pathname}`,
);
